# Generated by Django 2.1.7 on 2019-04-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_market_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperecord',
            options={'ordering': ('dish__name', 'ingredient__name')},
        ),
    ]
